version: "3.9"

networks:
  default:
    driver: bridge

services:
  mongo:
    image: mongo:4.2.3
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - default
  opentsdb:
    image: amdatu/opentsdbtest:latest
    container_name: opentsdb
    restart: always
    ports:
      - "4242:4242"
    volumes:
      - ./data/opentsdb:/data/opentsdb
    networks:
      - default
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - default
    depends_on:
      - opentsdb
      - mongo