name: 'Tests'

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'bugfix/') || startsWith(github.head_ref, 'hotfix/')
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: 'Install python ${{ matrix.python }}'
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.python }}
      - name: 'Install MongoDB'
        uses: supercharge/mongodb-github-actions@1.2.0
        with:
            mongodb-version: 4.4
      - name: 'Install dependencies'
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: 'Execute tests'
        run: coverage run -m unittest tests/test_*.py
      - name: 'Get coverage report'
        run: coverage report > coverage_${{ matrix.python }}.txt
      - name: 'Show coverage report'
        run: cat coverage_${{ matrix.python }}.txt
      - name: 'Upload coverage'
        uses: actions/upload-artifact@v2
        with:
          name: coverage_${{ matrix.python }}
          path: coverage_${{ matrix.python }}.txt